<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Datatable extends CI_Controller {
    function __construct() {
        parent::__construct();
        $this->load->library("dashtemp_template");
    }
    
    public function index() {
		$data = array();
        $this->dashtemp_template->display_dashtemp('page/datatable_vw', $data);
    }

    public function gridview() {
        $where = $this->input->post("where");
        
        $database = "default";
        $column = array('trans_id', 'trans_date', 'trans_type', 'trans_txt', 'trans_status', 'trans_amount');
        $table = "datatable";
        $list = $this->datatables_mdl->get_datatables($database, $table, $column, $where);
        $data = array();
        $no = $_POST['start'];
        foreach ($list as $line) 
        {
            $no++;          
            $row = array();
            $id = md5($line->trans_id);
            $link = '
                <div class="btn-group">
                  <a href="#" data-toggle="dropdown" style="color:#111"><i class="fa fa-folder-open"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#" style="color:#111" data-toggle="modal" data-target="#modalForm" onclick="generateModalView(\''.$line->trans_id.'\')">View</a></li>
                    <li><a href="#" style="color:#111" onclick="generateModalForm(\'edit\', \''.$line->trans_id.'\')">Update</a></li>
                    <li><a href="#" style="color:#111" onclick="doDelete(\''.$line->trans_id.'\')">Delete</a></li>
                  </ul>
                </div>
            ';
            $row[] = '<div style="text-align:center">'.$link.'</div>';
            $row[] = '<div style="text-align:center">'.$line->trans_id.'</div>';
            $row[] = '<div style="text-align:center">'.date("m/d/Y", strtotime($line->trans_date)).'</div>';
            $row[] = '<div style="text-align:center">'.$line->trans_type.'</div>';
            $row[] = '<div style="text-align:center">'.$line->trans_txt.'</div>';
            $row[] = '<div style="text-align:center">'.$line->trans_status.'</div>';
            $row[] = '<div style="text-align:center">'.$line->trans_amount.'</div>';
            $data[] = $row;
        }
 
        $output = array(
            "draw" => $_POST['draw'],
            "recordsTotal" => $this->datatables_mdl->count_all($database, $table, $column),
            "recordsFiltered" => $this->datatables_mdl->count_filtered($database, $table, $column, $where),
            "data" => $data,
        );
        
        echo json_encode($output);
    }

    public function generateId(){
        $qry = "select max(ifnull(trans_id, '00000')) as total from datatable where year(created_date) = '".date("Y")."'";
        $rs = getByQuery($qry);
        $last = (int)right($rs[0]->total, 5) + 1;
        $id = "TR".right(date("Y"), 2).right("00000".$last, 5);
        return $id;
    }

    public function save()
    {
        $txtstate = $this->input->post("txtstate");
        $txttransid = $this->input->post("txttransid");
        $txttransdate = $this->input->post("txttransdate");
        $ddltranstype = $this->input->post("ddltranstype");
        $txttranstxt = $this->input->post("txttranstxt");
        $ddltransstatus = $this->input->post("ddltransstatus");
        $txttransamount = $this->input->post("txttransamount");

        if($txtstate == 'add')
        {
            $insert = array(
                'trans_id' => $this->generateId(),
                'trans_date' => date("Y-m-d H:i:s", strtotime($txttransdate)),
                'trans_type' => $ddltranstype,
                'trans_txt' => $txttranstxt, 
                'trans_status' => $ddltransstatus,   
                'trans_amount' => $txttransamount,
                'created_date' => date("Y-m-d H:i:s")         
            );
            insertData("datatable", $insert);
            $data['msg'] = "Process successful";
            echo json_encode($data);
        }
        else
        {            
            $update = array(
                'trans_date' => date("Y-m-d H:i:s", strtotime($txttransdate)),
                'trans_type' => $ddltranstype,
                'trans_txt' => $txttranstxt, 
                'trans_status' => $ddltransstatus,   
                'trans_amount' => $txttransamount,
                'updated_date' => date("Y-m-d H:i:s")              
            );
            updateData("datatable", $update, "trans_id = '".$txttransid."'");
            $data['msg'] = "Process successful";
            echo json_encode($data);
        }
    }

    public function form() {
        $txtstate = $this->input->post("txtstate");
        $txttransid = $this->input->post("txttransid");
        $trans_id = "Generated by system";
        $trans_date = "";
        $trans_type = "";
        $trans_txt = "";
        $trans_status = "";
        $trans_amount = "";

        if($txtstate == "edit") {
            $qry = "select * from datatable where trans_id = '".$txttransid."'";
            $rs = getByQuery($qry);
            if($rs != "") {
                $trans_id = $rs[0]->trans_id;
                $trans_date = date("Y-m-d", strtotime($rs[0]->trans_date));
                $trans_type = $rs[0]->trans_type;
                $trans_txt = $rs[0]->trans_txt;
                $trans_status = $rs[0]->trans_status;
                $trans_amount = $rs[0]->trans_amount;
            }
        }

        $selected_draft = ($trans_status == "Draft") ? "selected" : "";
        $selected_approved = ($trans_status == "Approved") ? "selected" : "";;
        $selected_posted = ($trans_status == "Posted") ? "selected" : "";;
        $selected_invoice = ($trans_type == "Invoice") ? "selected" : "";;
        $selected_payment = ($trans_type == "Payment") ? "selected" : "";;
        $status_list = '
                <option value="Draft"'.$selected_draft.'>Draft</option>
                <option value="Approved"'.$selected_approved.'>Approved</option>
                <option value="Posted"'.$selected_posted.'>Posted</option>
            ';
        $type_list = '
                <option value="Invoice"'.$selected_invoice.'>Invoice</option>
                <option value="Payment"'.$selected_payment.'>Payment</option>
            ';

        $table = '
            <div class="row">

              <div class="col-md-12">
                <div class="form-group">
                  <label>Id: </label>
                  <input type="text" id="txttransid" name="txttransid" class="form-control" value="'.$trans_id.'" style="background:#fff" readonly />
                  <input type="hidden" id="txtstate" name="txtstate" class="form-control" value="'.$txtstate.'" />
                </div>
              </div>

              <div class="col-md-6">
                <div class="form-group">
                  <label>Date (mm/dd/yyyy):</label>
                  <input type="date" id="txttransdate" name="txttransdate" class="form-control" value="'.$trans_date.'" required />
                </div>
              </div>

              <div class="col-md-12">
                <div class="form-group">
                  <label>Type:</label>
                  <select id="ddltranstype" name="ddltranstype" class="form-control"  required>
                    <option value=""></option>
                    '.$type_list.'
                  </select>
                </div>
              </div>

              <div class="col-md-12">
                <div class="form-group">
                  <label>Description:</label>
                  <textarea id="txttranstxt" name="txttranstxt" rows="4" class="form-control">'.$trans_txt.'</textarea>
                </div>
              </div>

              <div class="col-md-12">
                <div class="form-group">
                  <label>Status:</label>
                  <select id="ddltransstatus" name="ddltransstatus" class="form-control"  required>
                    <option value=""></option>
                    '.$status_list.'
                  </select>
                </div>
              </div>

              <div class="col-md-12">
                <div class="form-group">
                  <label>Amount:</label>
                  <input type="text" id="txttransamount" name="txttransamount" class="form-control" value="'.$trans_amount.'" />
                </div>
              </div>
            </div>
        ';

        $data['table'] = $table;
        echo json_encode($data);
    }

    public function view() {
        $txttransid = $this->input->post("txttransid");
        $trans_id = "";
        $trans_date = "";
        $trans_type = "";
        $trans_txt = "";
        $trans_status = "";
        $trans_amount = "";
        
        $qry = "select * from datatable where trans_id = '".$txttransid."'";
        $rs = getByQuery($qry);
        if($rs != "") {
            $trans_id = $rs[0]->trans_id;
            $trans_date = date("m/d/Y", strtotime($rs[0]->trans_date));
            $trans_type = $rs[0]->trans_type;
            $trans_txt = $rs[0]->trans_txt;
            $trans_status = $rs[0]->trans_status;
            $trans_amount = $rs[0]->trans_amount;
        }        

        $table = '
            <table id="tablelist" class="table table-striped">
              <tbody>
                <tr>
                    <td style="width:25%" class="view-title">Id:</td>
                    <td class="view-txt">'.$trans_id.'</td>
                </tr>
                <tr>
                    <td class="view-title">Date:</td>
                    <td class="view-txt">'.$trans_date.'</td>
                </tr>
                <tr>
                    <td class="view-title">Type:</td>
                    <td class="view-txt">'.$trans_type.'</td>
                </tr>
                <tr>
                    <td class="view-title">Description:</td>
                    <td class="view-txt">'.$trans_txt.'</td>
                </tr>
                <tr>
                    <td class="view-title">Status:</td>
                    <td class="view-txt">'.$trans_status.'</td>
                </tr>
                <tr>
                    <td class="view-title">Amount:</td>
                    <td class="view-txt">'.$trans_amount.'</td>
                </tr>
              </tbody>
            </table>
        ';

        $data['table'] = $table;
        echo json_encode($data);
    }

    public function delete(){
        $txttransid = $this->input->post("txttransid");
        deleteData("datatable", "trans_id = '".$txttransid."'");
        $data['msg'] = "Process successful";
        echo json_encode($data);
    }
}	